#:schema node_modules/wrangler/config-schema.json
name = "bolt"
compatibility_flags = ["nodejs_compat_v2"]
compatibility_date = "2025-03-10"
pages_build_output_dir = "./build/client"
send_metrics = false
